# Generated by Django 5.2.15 on 2026-06-21 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('variant_label', models.CharField(blank=True, max_length=100)),
                ('student_prompt', models.TextField(blank=True)),
                ('generated_code', models.TextField(blank=True)),
                ('stdout_log', models.TextField(blank=True)),
                ('stderr_log', models.TextField(blank=True)),
                ('output_image', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('PRELOADED', 'Pre-loaded scenario dataset'), ('UPLOAD', 'Student-uploaded CSV')], default='PRELOADED', max_length=20)),
                ('uploaded_csv', models.FileField(blank=True, null=True, upload_to='uploads/neural_network/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neural_network_experiments', to='scenarios.scenario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neural_network_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
