# Generated by Django 5.2.15 on 2026-06-20 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('REGRESSION', 'Linear Regression'), ('CLASSIFICATION', 'Classification'), ('NEURAL_NETWORK', 'Neural Network')], db_index=True, max_length=20)),
                ('challenge', models.TextField()),
                ('takeaway', models.TextField()),
                ('try_it_out', models.TextField()),
                ('icon', models.CharField(default='🔬', help_text='Emoji shown on the card', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the model type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'ordering': ['model_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DataVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier used internally, e.g. perfect / messy / tiny', max_length=50)),
                ('label', models.CharField(help_text='Human-readable name shown in UI', max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'name')},
            },
        ),
    ]
